apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infra
  namespace: argocd
spec:
  description: infrastructure applications

  sourceRepos:
    - https://github.com/Dialgatrainer02-lab/apps.git

  destinations:
    - namespace: '!kube-system'
      server: '*'

  clusterResourceWhitelist:
    # CRDs
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition

    # Admission webhooks
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration

    # RBAC
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding

    # cert-manager
    - group: cert-manager.io
      kind: ClusterIssuer

  namespaceResourceWhitelist:
    - group: apps
      kind: Deployment
    - group: apps
      kind: StatefulSet
    - group: apps
      kind: DaemonSet
    - group: batch
      kind: Job
    - group: ''
      kind: Service
    - group: ''
      kind: ServiceAccount
    - group: ''
      kind: ConfigMap
    - group: ''
      kind: Secret
    - group: gateway.networking.k8s.io
      kind: Gateway
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
    - group: gateway.networking.k8s.io
      kind: TCPRoute

  orphanedResources:
    warn: true
