{{- define "lib.gateway" }}
{{- if .Values.gateway.enabled }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
  {{- with .Values.gateway.annotations }}
  annotations:
    {{- toYaml . | nindent 2 }}
  {{- end }}
spec:
  gatewayClassName: {{ .Values.gateway.className }}
  listeners:
  {{- range .Values.gateway.listeners }}
  - name: {{ .name }}
    protocol: {{ .protocol | default "HTTPS" }}
    port: {{ .port | default "443" }}
    hostname: {{ .host }}
    tls:
      certificateRefs:
      - kind: Secret
        name: {{ .tls.secretName }}
  {{- end }}
---
{{- end }}
{{- end }}