{{- define "gateway-lib.gateway" -}}
{{- if .Values.gateway.enabled }}

apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ default (include "gateway-lib.fullname" .) .Values.gateway.name }}
  labels:
    {{- include "gateway-lib.labels" . | nindent 4 }}
  {{- with .Values.gateway.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  gatewayClassName: {{ .Values.gateway.className }}
  listeners:
    {{- toYaml .Values.gateway.listeners | nindent 4 }}

{{- end }}
{{- end }}
