{{- define "lib.httproute" }}
{{- if .Values.httpRoute.enabled }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "test.labels" . | nindent 4 }}
  {{- with .Values.httpRoute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
    {{- toYaml .Values.httpRoute.parentRefs | nindent 4 }}

  {{- with .Values.httpRoute.hostnames }}
  hostnames:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  rules:
  {{- range .Values.httpRoute.rules }}
  - {{- with .matches }}
    matches:
      {{- toYaml . | nindent 6 }}
    {{- end }}

    {{- with .filters }}
    filters:
      {{- toYaml . | nindent 6 }}
    {{- end }}

    backendRefs:
      {{- toYaml .backendRefs | nindent 6 }}
  {{- end }}
---
{{- end }}
{{- end }}
