{{- define "gateway-lib.httproutes" -}}
{{- if .Values.httpRoutes.enabled }}

{{- range $index, $route := .Values.httpRoutes.items }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $route.name | default (printf "%s-%d" (include "lib.fullname" $) $index) }}
  labels:
    {{- include "lib.labels" $ | nindent 4 }}
  {{- with $route.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
    {{- toYaml $route.parentRefs | nindent 4 }}
  {{- with $route.hostnames }}
  hostnames:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    {{- toYaml $route.rules | nindent 4 }}

{{- end }}
{{- end }}
{{- end }}
