{{- define "gateway-lib.httproute" -}}
{{- if .Values.httpRoute.enabled }}

apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ default (include "gateway-lib.fullname" .) .Values.httpRoute.name }}
  labels:
    {{- include "gateway-lib.labels" . | nindent 4 }}
spec:
  parentRefs:
    {{- toYaml .Values.httpRoute.parentRefs | nindent 4 }}
  hostnames:
    {{- toYaml .Values.httpRoute.hostnames | nindent 4 }}
  rules:
    {{- toYaml .Values.httpRoute.rules | nindent 4 }}

{{- end }}
{{- end }}
