{{- define "lib.secrets" }}
{{- if .Values.secrets.enabled }}
{{- range .Values.secrets.items }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  {{- with .namespace }}
  namespace: {{ . }}
  {{- end }}
  labels:
    {{- include "lib.labels" $ | nindent 4 }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: {{ .type | default "Opaque" }}

{{- if .stringData }}
stringData:
  {{- range $key, $val := .stringData }}
  {{ $key }}: {{- if eq $val "__RANDOM__" }} {{ randAlphaNum 32 }} {{- else }} {{ $val | quote }} {{- end }}
  {{- end }}
{{- end }}

{{- if .data }}
data:
  {{- toYaml .data | nindent 2 }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
