{{- define "lib.secrets" }}
{{- if .Values.secrets.enabled }}
{{- range .Values.secrets.items }}
{{- $existing := lookup "v1" "Secret" $.Release.Namespace .name }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
type: {{ .type | default "Opaque" }}
stringData:
  {{- range $key, $val := .stringData }}
  {{ $key }}: |
    {{- if and (eq $val "__RANDOM__") (not $existing) }}
    {{ randAlphaNum 32 }}
    {{- else if eq $val "__RANDOM__" }}
    {{ index $existing.data $key | b64dec }}
    {{- else }}
    {{ $val }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
